/* Social Feed */
export const HANDLE_SET_POSTS_LIST = 'HANDLE_SET_POSTS_LIST';
export const HANDLE_SET_POST_ID = 'HANDLE_SET_POST_ID';
export const HANDLE_SET_RELOAD_POSTS = 'HANDLE_SET_RELOAD_POSTS';
